---
apiVersion: v1
kind: Namespace
metadata:
  name: runtime-rundown
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    istio-injection: enabled
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: runtime-rundown-blueprint
  namespace: runtime-rundown
spec:
  interval: 1m
  ref:
    tag: v0.1.0
  url: oci://172.30.1.2:5000/library/runtime-rundown
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runtime-rundown-blueprint
  namespace: runtime-rundown
spec:
  interval: 10m
  path: ./
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: runtime-rundown-blueprint
